# Travis CI configuration for upmake.
language: perl
perl:
    - "5.10"
    - "5.14"
    - "5.20"

env: PERL_CPANM_OPT="--notest --force --skip-satisfied"

install:
    - "dzil listdeps | cpanm"
    - "dzil authordeps --missing | cpanm"
    - "cpanm Pod::Coverage::TrustPod"

script: "dzil test --release"

notifications:
  email:
    recipients:
      - vz-upmake@zeitlins.org
