# Travis CI configuration for upmake.
language: perl
perl:
    - "5.10"
    - "5.14"
    - "5.20"

env:
    global:
        - PERL_CPANM_OPT="--notest --force --skip-satisfied"
        - RELEASE_TESTING=1
        - AUTOMATED_TESTING=1
        - AUTHOR_TESTING=1
        - HARNESS_OPTIONS=c
        - HARNESS_TIMER=1

install:
    - "dzil listdeps | cpanm"
    - "dzil authordeps --missing | cpanm"
    - "cpanm Pod::Coverage::TrustPod"
    - cpanm Devel::Cover::Report::Coveralls

script:
    - dzil build
    - PERL5OPT="-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine+ignore=prove" prove -lrv t
    - cover

after_success:
    - cover -report coveralls

notifications:
  email:
    recipients:
      - vz-upmake@zeitlins.org
